name: Continuous Integration
on: [push, pull_request]

jobs:
  linux-tests:
    name: Linux Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_args: [servers, chain, core, keychain, pool, p2p, src, api, util, store]
    steps:
      - uses: actions/checkout@v3
      - name: Test ${{ matrix.job_args }}
        working-directory: ${{ matrix.job_args }}
        run: cargo test --release

  macos-intel-tests:
    name: macOS Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests (Intel)
        run: cargo test --release --all

  macos-arm-tests:
    name: macOS Tests
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests (ARM64)
        run: cargo test --release --all --target aarch64-apple-darwin

  windows-tests:
    name: Windows Tests
    runs-on: windows-2019
    env:
      ROARING_ARCH: x86-64-v2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tests
        run: cargo test --release --all